config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations", unlocks: "users/unlocks" }

  devise_for :welfares, controllers: { registrations: "welfares/registrations", sessions: "welfares/sessions", passwords: "welfares/passwords", confirmations: "welfares/confirmations", unlocks: "welfares/unlocks" }

  root to: "pages/tops#index"

  # ! 動物愛護団体関連
  # * 投稿関連
  get "welfares/posts/new", to: "welfares/posts#new"
  post "welfares/posts/create", to: "welfares/posts#create"
  get "welfares/posts/show/:post_id", to: "welfares/posts#show"
  get "welfares/posts/edit/:post_id", to: "welfares/posts#edit"
  patch "welfares/posts/update/:post_id", to: "welfares/posts#update"
  delete "welfares/posts/destroy/:post_id", to: "welfares/posts#destroy"
  # * プロフィール関連
  get "welfares/profiles", to: "welfares/profiles#show"
end

app/models/welfare.rb
class Welfare < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/welfares/confirmations_controller.rb
# frozen_string_literal: true

class Welfares::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/welfares/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Welfares::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/welfares/passwords_controller.rb
# frozen_string_literal: true

class Welfares::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/welfares/posts/posts_controller.rb
class Welfares::Posts::PostsController < ApplicationController
  # ! ログインが必要な処理
  before_action :authenticate_welfare!, only: [:new, :edit, :update, :destroy]

  # ! 投稿を新規作成するメソッド
  def new
    @post = WelfarePost.new
  end

  # ! 投稿を新規作成するメソッド
  def create
    @post = WelfarePost.new(post_params)

    # * ログインしている愛護団体のIDを挿入
    @post.welfare_id = current_welfare.id

    if @post.save
      redirect_to "/"
    else
      render :new
    end
  end

  private

  # ! ペットの情報を投稿時にバインドするパラメータ
  def post_params
    params.require(:welfare_post).permit(:image, :title, :profile, :appeal_point, :age, :kinds, :price)
  end
end

app/controllers/welfares/posts_controller.rb
class Welfares::PostsController < ApplicationController
  # ! ログインが必要な処理
  before_action :authenticate_welfare!, only: [:show, :new, :create, :edit, :update, :destroy]

  # ! 投稿の詳細を表示するメソッド
  def show
    @post = WelfarePost.find(params[:post_id])

    # * 投稿者でない場合はリダイレクトする
    if @post.welfare_id != current_welfare.id
      redirect_to "/welfares/profiles"
    end
  end

  # ! 投稿を新規作成するメソッド
  def new
    @post = WelfarePost.new
  end

  # ! 投稿を新規作成するメソッド
  def create
    @post = WelfarePost.new(post_params)

    # * ログインしている愛護団体のIDを挿入
    @post.welfare_id = current_welfare.id

    if @post.save
      redirect_to "welfares/profiles"
    else
      render :new
    end
  end

  # ! 投稿を編集するメソッド
  def edit
    @post = WelfarePost.find(params[:post_id])

    # * 投稿者でない場合はリダイレクトする
    if @post.welfare_id != current_welfare.id
      redirect_to "/welfares/profiles"
    end
  end

  # ! 投稿を編集するメソッド
  def update
    @post = WelfarePost.find(params[:post_id])

    # * 投稿者でない場合はリダイレクトする
    if @post.welfare_id != current_welfare.id
      redirect_to "/welfares/profiles"
    end

    if @post.update(post_params)
      redirect_to "/welfares/profiles"
    else
      redirect_to "/welfares/profiles"
    end
  end

  def destroy
    @post = WelfarePost.find(params[:post_id])

    # * 投稿者でない場合はリダイレクトする
    if @post.welfare_id != current_welfare.id
      redirect_to "/welfares/profiles"
    end

    if @post.destroy
      redirect_to "/welfares/profiles"
    else
      redirect_to "/welfares/post"
    end
  end

  private

  # ! ペットの情報を投稿時にバインドするパラメータ
  def post_params
    params.require(:welfare_post).permit(:image, :title, :profile, :appeal_point, :age, :kinds, :price)
  end
end

app/controllers/welfares/profiles_controller.rb
class Welfares::ProfilesController < ApplicationController
  # ! ログインが必要な処理
  before_action :authenticate_welfare!, only: [:show, :edit, :update, :destroy]

  def show
    @posts = WelfarePost.where(welfare_id: current_welfare.id).order(created_at: "DESC")
  end
end

app/controllers/welfares/registrations_controller.rb
# frozen_string_literal: true

class Welfares::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:group_name, :address, :tel])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welfares/sessions_controller.rb
# frozen_string_literal: true

class Welfares::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/welfares/unlocks_controller.rb
# frozen_string_literal: true

class Welfares::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/welfares/posts_helper.rb
module Welfares::PostsHelper
end

app/helpers/welfares/profiles_helper.rb
module Welfares::ProfilesHelper
end

app/views/welfares/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "welfares/components/sidebar" %>
    </div>
    <div class="col-lg-9">
      <div class="col-lg-8 mx-auto">
        <% if @post.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <% @post.errors.each do |error| %>
              <strong>エラー！</strong> - <%= error.full_message %><br>
            <% end %>
          </div>
        <% end %>
        <%= form_with(model: @post, url: "/welfares/posts/update/#{@post.id}", local: true) do |f| %>
          <div class="mb-3">
            <div class="d-flex align-items-center">
              <div class="col-lg-8">
                <%= f.label "掲載する動物の画像", class: "form-label" %>
                <%= f.file_field :image, class: "form-control" %>
              </div>
              <div class="col-lg-4 form-image-box">
                <%= image_tag(@post.image.url, class: "form-image mx-auto") %>
              </div>
            </div>
          </div>
          <div class="mb-3">
            <%= f.label "掲載するタイトル", class: "form-label" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物の紹介", class: "form-label" %>
            <%= f.text_area :profile, class: "form-control", rows: 5 %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物のアピールポイント", class: "form-label" %>
            <%= f.text_area :appeal_point, class: "form-control", rows: 5 %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物の年齢", class: "form-label" %>
            <%= f.number_field :age, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物の種類", class: "form-label" %>
            <%= f.text_field :kinds, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "お迎え費用（*発生しない場合は何も記載しないでください。）", class: "form-label" %>
            <%= f.number_field :price, class: "form-control" %>
          </div>
          <%= f.submit "情報を掲載する", class: "btn btn-primary px-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welfares/posts/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-lg-3">
      <%= render "welfares/components/sidebar" %>
    </div>
    <div class="col-lg-9 bg-white py-4">
      <div class="col-lg-8 mx-auto">
        <% if @post.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <% @post.errors.each do |error| %>
              <strong>エラー！</strong> - <%= error.full_message %><br>
            <% end %>
          </div>
        <% end %>
        <%= form_with(model: @post, url: welfares_posts_create_path, local: true) do |f| %>
          <div class="mb-3">
            <%= f.label "掲載する動物の画像", class: "form-label" %>
            <%= f.file_field :image, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載するタイトル", class: "form-label" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物の紹介", class: "form-label" %>
            <%= f.text_area :profile, class: "form-control", rows: 5 %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物のアピールポイント", class: "form-label" %>
            <%= f.text_area :appeal_point, class: "form-control", rows: 5 %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物の年齢", class: "form-label" %>
            <%= f.number_field :age, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "掲載する動物の種類", class: "form-label" %>
            <%= f.text_field :kinds, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label "お迎え費用（*発生しない場合は何も記載しないでください。）", class: "form-label" %>
            <%= f.number_field :price, class: "form-control" %>
          </div>
          <%= f.submit "情報を掲載する", class: "btn btn-primary px-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welfares/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "welfares/components/sidebar" %>
    </div>
    <div class="col-lg-9">
      <div class="card bg-dark text-white col-lg-7 mx-auto">
        <div class="bg_dark">
          <%= image_tag(@post.image.url, class: "card-img animal-image-detail") %>
        </div>
        <div class="card-img-overlay">
          <h5 class="card-title text-white fw-bold"><%= @post.title %></h5>
          <p class="card-text text-white"><%= @post.kinds %> &#047; <%= @post.age %>歳</p>
        </div>
      </div>
      <div class="my-5 py-5 col-lg-7 mx-auto">
        <h4 class="detail-title"><%= @post.title %></h4>
        <div class="my-4">
          <h5>自己紹介</h5>
          <p><%= @post.profile %></p>
        </div>
        <div class="my-4">
          <h5>性格・アピールポイント</h5>
          <p><%= @post.appeal_point %></p>
        </div>
        <div class="my-4">
          <h5>種類・年齢</h5>
          <p><%= @post.kinds %> &#047; <%= @post.age %>歳</p>
        </div>
        <div class="my-4">
          <h5>お迎え費用</h5>
          <p>
            <% if @post.price == nil %>
              お迎え費用は発生しません。
            <% else %>
              ¥<%= @post.price %>
            <% end %>
          </p>
        </div>
        <div class="my-4">
          <h5>ボタン類</h5>
          <%= link_to "Some Page" do %>
            <button>編集</button>
          <% end %>
          <%= link_to "Some Page" do %>
            <button>削除</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>